version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pokemon-db
    environment:
      POSTGRES_USER: yourUsername
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pokemon-network
    restart: always

  spring-boot-app:
    build: ./path-to-your-spring-boot-app # specify the path to your Spring Boot app if you are building it
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pokemon_db
      SPRING_DATASOURCE_USERNAME: yourUsername
      SPRING_DATASOURCE_PASSWORD: yourPassword
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - pokemon-network
    restart: always

networks:
  pokemon-network:
    driver: bridge

volumes:
  postgres-data:
