# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: poke_db
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init.sql

